export const DEMAND_STATUSES = {
  PENDING: "PENDING",
  OPEN: "OPEN",
  MATCHED: "MATCHED",
  ASSIGNED: "ASSIGNED",
  DEPARTED: "DEPARTED",
  ARRIVED: "ARRIVED",
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const

export type DemandStatus = (typeof DEMAND_STATUSES)[keyof typeof DEMAND_STATUSES]

const VALID_TRANSITIONS: Record<string, string[]> = {
  [DEMAND_STATUSES.PENDING]: [DEMAND_STATUSES.OPEN, DEMAND_STATUSES.CANCELLED],
  [DEMAND_STATUSES.OPEN]: [DEMAND_STATUSES.MATCHED, DEMAND_STATUSES.CANCELLED],
  [DEMAND_STATUSES.MATCHED]: [DEMAND_STATUSES.ASSIGNED, DEMAND_STATUSES.CANCELLED],
  [DEMAND_STATUSES.ASSIGNED]: [DEMAND_STATUSES.DEPARTED, DEMAND_STATUSES.CANCELLED],
  [DEMAND_STATUSES.DEPARTED]: [DEMAND_STATUSES.ARRIVED, DEMAND_STATUSES.CANCELLED],
  [DEMAND_STATUSES.ARRIVED]: [DEMAND_STATUSES.STARTED, DEMAND_STATUSES.CANCELLED],
  [DEMAND_STATUSES.STARTED]: [DEMAND_STATUSES.COMPLETED],
  [DEMAND_STATUSES.COMPLETED]: [],
  [DEMAND_STATUSES.CANCELLED]: [],
}

export function validateDemandTransition(from: string, to: string): string | null {
  const allowed = VALID_TRANSITIONS[from]
  if (!allowed) return `未知状态: ${from}`
  if (!allowed.includes(to)) return `不允许从 ${from} 转换到 ${to}`
  return null
}
