ALTER TABLE credit_records
  ADD COLUMN IF NOT EXISTS integrity_score NUMERIC(5,2) DEFAULT 60,
  ADD COLUMN IF NOT EXISTS capability_score NUMERIC(5,2) DEFAULT 60,
  ADD COLUMN IF NOT EXISTS reliability_score NUMERIC(5,2) DEFAULT 60,
  ADD COLUMN IF NOT EXISTS communication_score NUMERIC(5,2) DEFAULT 60,
  ADD COLUMN IF NOT EXISTS safety_score NUMERIC(5,2) DEFAULT 60,
  ADD COLUMN IF NOT EXISTS contribution_score NUMERIC(5,2) DEFAULT 60;
